language: node_js
branches:
  only:
    - master
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - set -e
  - npm test
  - cp -av ./public/. ./dist/
  - npm run build
  - set +e
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_deploy_token
  local_dir: dist
  on:
    branch: master
deploy:
  provider: surge
  skip_cleanup: true
  project: ./dist/
  domain: https://shawnpetros.com
  on:
    branch: master
